import { Match, User, Prediction, LeaderboardEntry } from '@/types'

export const MOCK_MATCHES: Match[] = [
  {
    id: '1',
    home_team: 'Brazil',
    away_team: 'Argentina',
    home_flag: '🇧🇷',
    away_flag: '🇦🇷',
    kickoff_at: '2026-06-14T15:00:00Z',
    round: 'Group Stage',
    group_name: 'Group A',
    status: 'completed',
    manually_locked: false,
    home_score: 2,
    away_score: 1,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '2',
    home_team: 'France',
    away_team: 'Germany',
    home_flag: '🇫🇷',
    away_flag: '🇩🇪',
    kickoff_at: '2026-06-15T15:00:00Z',
    round: 'Group Stage',
    group_name: 'Group B',
    status: 'voting_open',
    manually_locked: false,
    home_score: null,
    away_score: null,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '3',
    home_team: 'England',
    away_team: 'Spain',
    home_flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    away_flag: '🇪🇸',
    kickoff_at: '2026-06-15T18:30:00Z',
    round: 'Group Stage',
    group_name: 'Group C',
    status: 'locked',
    manually_locked: true,
    home_score: null,
    away_score: null,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '4',
    home_team: 'Portugal',
    away_team: 'Morocco',
    home_flag: '🇵🇹',
    away_flag: '🇲🇦',
    kickoff_at: '2026-06-16T19:00:00Z',
    round: 'Group Stage',
    group_name: 'Group A',
    status: 'upcoming',
    manually_locked: false,
    home_score: null,
    away_score: null,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '5',
    home_team: 'Spain',
    away_team: 'Germany',
    home_flag: '🇪🇸',
    away_flag: '🇩🇪',
    kickoff_at: '2026-06-17T15:00:00Z',
    round: 'Group Stage',
    group_name: 'Group C',
    status: 'upcoming',
    manually_locked: false,
    home_score: null,
    away_score: null,
    created_at: '2026-06-01T00:00:00Z',
  },
  {
    id: '6',
    home_team: 'Mexico',
    away_team: 'USA',
    home_flag: '🇲🇽',
    away_flag: '🇺🇸',
    kickoff_at: '2026-06-13T20:00:00Z',
    round: 'Group Stage',
    group_name: 'Group D',
    status: 'completed',
    manually_locked: false,
    home_score: 1,
    away_score: 3,
    created_at: '2026-06-01T00:00:00Z',
  },
]

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Rahul Menon',
  email: 'rahul.menon@company.com',
  is_admin: false,
  created_at: '2026-01-01T00:00:00Z',
}

export const MOCK_PREDICTIONS: Prediction[] = [
  {
    id: 'p1',
    user_id: 'user-1',
    match_id: '1',
    predicted_winner: 'home',
    goal_difference: 2,
    points_earned: 15,
    created_at: '2026-06-13T10:00:00Z',
  },
  {
    id: 'p2',
    user_id: 'user-1',
    match_id: '2',
    predicted_winner: 'home',
    goal_difference: 1,
    points_earned: 0,
    created_at: '2026-06-14T10:00:00Z',
  },
  {
    id: 'p3',
    user_id: 'user-1',
    match_id: '6',
    predicted_winner: 'away',
    goal_difference: 2,
    points_earned: 10,
    created_at: '2026-06-12T10:00:00Z',
  },
]

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { user_id: 'u1', name: 'Jamie Moreno',    email: 'jamie@company.com',   total_points: 125, correct_predictions: 9,  total_predictions: 12 },
  { user_id: 'u2', name: 'Priya Sharma',    email: 'priya@company.com',   total_points: 115, correct_predictions: 8,  total_predictions: 12 },
  { user_id: 'u3', name: 'Aaron Osei',      email: 'aaron@company.com',   total_points: 105, correct_predictions: 8,  total_predictions: 12 },
  { user_id: 'user-1', name: 'Rahul Menon', email: 'rahul@company.com',   total_points: 75,  correct_predictions: 6,  total_predictions: 12 },
  { user_id: 'u5', name: 'Sneha Kumar',     email: 'sneha@company.com',   total_points: 65,  correct_predictions: 5,  total_predictions: 11 },
  { user_id: 'u6', name: 'Dev Patel',       email: 'dev@company.com',     total_points: 60,  correct_predictions: 5,  total_predictions: 12 },
  { user_id: 'u7', name: 'Lena Fischer',    email: 'lena@company.com',    total_points: 55,  correct_predictions: 4,  total_predictions: 10 },
  { user_id: 'u8', name: 'Carlos Rivera',   email: 'carlos@company.com',  total_points: 45,  correct_predictions: 4,  total_predictions: 12 },
  { user_id: 'u9', name: 'Yuki Tanaka',     email: 'yuki@company.com',    total_points: 40,  correct_predictions: 3,  total_predictions: 9  },
  { user_id: 'u10', name: 'Sophie Chen',    email: 'sophie@company.com',  total_points: 30,  correct_predictions: 3,  total_predictions: 12 },
]

export const MOCK_VOTERS = {
  '3': {
    home: [
      { name: 'Jamie Moreno',  initials: 'JM', color: '#E8C887', diff: 1 },
      { name: 'Aaron Osei',    initials: 'AO', color: '#87C8E8', diff: 2 },
      { name: 'Rahul Menon',   initials: 'RM', color: '#E887C8', diff: 1 },
    ],
    draw: [
      { name: 'Priya Sharma',  initials: 'PS', color: '#87E8C8', diff: null },
    ],
    away: [
      { name: 'Sneha Kumar',   initials: 'SK', color: '#C8E887', diff: 2 },
      { name: 'Dev Patel',     initials: 'DP', color: '#C887E8', diff: 1 },
    ],
  },
}
